[workspace]
resolver = '2'
members = [
    'discord_bot',
    'telegram_bot',
    'libs/core', "libs/user",
]

[profile.release]
lto = true

[workspace.dependencies]
core = { path = "libs/core" }
user = { path = "libs/user" }