# on:
#   release:
#     types: [published]
# jobs:
#   release:
#     name: release ${{ matrix.target }}
#     runs-on: ubuntu-latest
#     strategy:
#       fail-fast: false
#       matrix:
#         target: [x86_64-unknown-linux-musl]
#         package: [discord_bot]
#     steps:
#       - uses: actions/checkout@master
#       - name: Compile and release
#         uses: rust-build/rust-build.action@v1.4.5
#         env:
#           SRC_DIR: ${{ matrix.package }}
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           TOOLCHAIN_VERSION: 1.85.0
#         with:
#           RUSTTARGET: ${{ matrix.target }}
#           EXTRA_FILES: "README.md LICENSE"
#   docker-realease:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v3
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3
#       - name: Login to GitHub Container Registry
#         uses: docker/login-action@v3
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}
#       - name: Build and push
#         uses: docker/build-push-action@v6
#         with:
#           push: true
#           tags: ghcr.io/iziodev/spectre-tipper:${{ github.ref_name }},ghcr.io/iziodev/spectre-tipper:latest
